version: '3.8'

services:
  correlator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - CORR_NATS_URL=nats://nats:4222
      - CORR_HTTP_ADDR=:8082
      - CORR_HOT_RELOAD=false
    depends_on:
      - nats
    networks:
      - aegisflux
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  aegisflux:
    external: true
